# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'MyTwitter' do

pod 'AFNetworking'
pod 'BDBOAuth1Manager'
pod 'MBProgressHUD'
pod 'STTwitter'
pod 'DateTools'
#pull to refresh and infinite scroll widget
pod 'SVPullToRefresh'
pod 'UIColor-HexString'

end

target 'MyTwitterTests' do

end

